version: "3"

services:
  backend:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.app.production
    env_file:
      - .env
    ports:
      - ${BACKEND_PORT}:5000
      - ${BACKEND_PRISMA_PORT}:5555
    depends_on:
      - database

  database:
    image: postgres:15
    volumes:
      - database_data:/var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

volumes:
  database_data:
